# Generated by Django 4.1.3 on 2022-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('price', models.CharField(max_length=70)),
                ('food_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
