# Generated by Django 4.1.1 on 2022-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_food_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOODITEMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('food_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='FOOD',
        ),
    ]
